version: '3.7'

services:

    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus/data:/prometheus
        ports:
            - "9090:9090"
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'

    grafana:
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        volumes:
            - ./grafana/data:/var/lib/grafana/data
        depends_on:
            - prometheus

    zipkin:
        image: openzipkin/zipkin-slim
        ports:
            - "9411:9411"

    jaeger:
        image: jaegertracing/all-in-one
        environment:
            COLLECTOR_ZIPKIN_HOST_PORT: 9412

        ports:
            - "9412:9412"
            - "16686:16686"
