receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "collector:4317"
      http:
        endpoint: "collector:4318"

  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:
      paging:

processors:
  batch:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8882
    namespace: default

  zipkin:
    endpoint: zipkin:9411

  logging:
    verbosity: detailed

service:

  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]