global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'collector'
    static_configs:
      - targets: ['collector:8888']  
  - job_name: ‘nginx exporter’
    scrape_interval: 5s
    static_configs:
      - targets: ['172.23.203.138:9113']      